- name: "Install python apt modules"
  apt: name={{ item }} update_cache=yes
  with_items: "{{ python_apt_modules }}"

- name: "Upgrade python pip"
  pip: name=pip version=9.*

- name: "Install Python PIP modules"
  pip: name={{ item }}
  ignore_errors: yes
  with_items: "{{ python_pip_modules }}"
