---

- name: "MySQL | install mysql packages"
  apt: pkg={{ item }} state=installed
  become: yes
  become_method: "sudo"
  with_items: "{{ mysql_apt_modules }}"

#- name: "MySQL | create MySQL configuration file"
#  become: yes
#  become_method: "sudo"
#  template:
#    src=my.cnf.j2
#    dest=/etc/mysql/my.cnf
#    backup=yes
#    owner=root
#    group=root
#    mode=0644
#    force=yes

- name: "Create {{ mysql_db_user }} user"
  mysql_user:
    login_user=root
    login_password=''
    name={{ mysql_db_user }}
    password={{ mysql_db_pass }}
    priv=*.*:ALL,GRANT
    host={{ mysql_settings_host_connect }}
    state=present
  ignore_errors: True

- name: "Create {{ mysql_db_name }} database"
  mysql_db:
    name={{ mysql_db_name }}
    encoding=utf8
    state=present
    login_user={{ mysql_db_user }}
    login_password={{ mysql_db_pass }}
  ignore_errors: True

#- name: "MySQL | Remove the MySQL test database"
#  mysql_db:
#    db=test
#    state=absent
#    login_user={{ mysql_db_user }}
#    login_password={{ mysql_db_pass }}
#  ignore_errors: True

#- name: "Remove all root users"
#  mysql_user:
#    name=root
#    host_all=yes
#    state=absent
#  ignore_errors: True

#- name: "MySQL | restart mysql"
#  service:
#    name=mysql
#    state=restarted
#  become: yes
#  become_method: "sudo"
